### ISSUE TITLE
Term changes: Experiment Point/Site vs. Decision Point/Coordinated Decision Point

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#10]
Let's discuss how and what to finalize our terminology for Experiment Points/Experiment Sites (formerly Partitions). In a paper, @SritterCL referred to them as Decision Points (vs. Experiment Point) and Coordinated Decision Point (vs. Experiment Site) as a potentially more effective way of communicating the concepts involved. However, as Derek noted in today's meeting, we also want the concepts to be clear to whoever is working on/looking at the code and that terms make sense in the larger context. 

We've gone through a number of term changes with this project, and I'm hesitant to make yet another change unless we are _really sure_ about sticking with it, so let's discuss the following: 

1. What are the benefits from making this change?
2. What are the drawbacks?
3. Are there other terms that we might prefer?
4. How do these new terms fit in the context of the overall UpGrade architecture?

This may end up a meeting topic, but what is not good is if these terms float around for a while without any decision made about whether or not to use them. So let's aim for making a decision about this in the next 1-2 weeks. 

Tagging those involved: @SritterCL @nirmalpatel @jerith666 @msandbothe @VivekFitkariwala @ppratikcr7 - feel free to tag others.

**Comment by amurphy-cl** [comment]
Let's come to some decisions on this asap

**Comment by nirmalpatel** [comment]
I like the term "Experiment Point" as it explicitly has the word Experiment. The word "Decision" is more abstract, and it may or may not refer to an experiment. So I've been leaning more towards the term Experiment Point.

I think for the point/ID, having the terms "site" and "target" make sense to be because "site" is the "site in the code" where the experiment is happening (this, for us, is usually a function where conditional code execution happens). The word site has some analogy with construction sites, which denotes an actual place where things are happening. The word "target" makes sense because it refers to our target at the site, i.e., what particular thing we want to experiment with at our site.

So overall, my preference is Experiment Point = Site + Target. Anyway, this is my preference, and I'll let others share their ideas.

I agree that we need to decide this soon (and for the last time) - and then make a one-time change in the code that we don't hope to reverse.

**Comment by amurphy-cl** [comment]
@SritterCL let's make a final decision on this. Adding it to this week's agenda.

**Comment by ppratikcr7** [comment]
We can finalize the terminology for this [ticket](https://github.com/CarnegieLearningWeb/UpGrade/issues/250) here itself, so closing the mentioned ticket as its kind of duplicate.

**Comment by ppratikcr7** [comment]
Closing this issue as its completed in the frontend enhancement PR
