### ISSUE TITLE
Add request logging for errors

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1042]
We could help ourselves debug prod issues easier by putting request bodies onto error logs.

https://carnegielearning.slack.com/archives/C055CGCRP6Z/p1696815544069419?thread_ts=1696815538.859709&cid=C055CGCRP6Z

**Comment by amurphy-cl** [comment]
As with #1040, pasting the relevant info from slack below

We have not been able to replicate the errors or the scenario in prod on Monday after promoting v5, but here's what I do know:- Regardless of the root cause, we are catching ourselves in an error-state death cycle in some situations. Here's what Dan believes to be happening:

1.	Our Java library is retrying all errors 3 times, for a total of 4 error calls per endpoint being called, with no back-off strategy.
2.	Our TypeScript library is a little different/smarter. It does a some back-off between retries. It will retry only 4xx errors, not 5xx or unknown errors. I think that logic is exactly backwards though, as 4xx errors represent client mistakes and should theoretically never work if retried. 5xx or unknown errors are potentially retryable, as they are supposed to represent server / network errors.
3.	Every error to an endpoint is inserted into DB, so every retried error is also inserted into the database. This table is enormous in the prod database. The purpose of this table is that it can be queried easier than logs and it can be used to show errors to the experiment in the UI, but in practice it is producing a firehose of errors that can barely be queried at all.
4.	Every error produces extra logs as well, with same information, sometimes multiple times. We tend to see our instances go out of service due to 100% of file-system in use in these spells where our application performance nose-dives. This is probably due to the explosion of logging.
5.	Cumulatively, when a few errors start to happen across multiple endpoints for whatever reason, it quickly can escalate into a ricochet of errors that are getting retried and logged in database 4x each, which cascade into more errors because the environment has been degraded.

Dan would modestly propose a handful of straightforward measures we could put into v5 to majorly limit the ability of the system to spiral out of control and give us better logging when it starts to tilt.
1.	Cease inserting logging errors in database (temporary until a better strategy identified).
2.	Turn off or revert endpoint request validation (temporary until better testing, roll back on in waves).
3.	Log request bodies in legitimate 4xx bad request-type errors.
4.	Cap SDK response times at a much lower number with env var.
5.	Java lib, do not retry 4xx errors.
6.	Java lib, only retry once if error status is 5xx or unknown.
7.	TS lib, switch the current logic and also limit the retries on 5xx or unknown to once for the DefaultHttpClient.
8.	Put try/catch around experimentUserRepository.save and/or use upsert. (mitigates a specific query that fails sporadically but which seems to really upset the database when it happens, seeing same error that happened in Github bugfix #710 but suddenly in different endpoint, /init)

As for the root cause of the issues on Monday, I invite others to take a look, but I'm at the point where I don't think I can reproduce without trying out some of the above ideas and seeing if we can't catch it in the act again by promoting v5 to prod so we can see the requests.Only the v1 endpoints that Mathia calls via the v3 java lib were producing Bad Request errors, and there was at least 1 Query Failed due to inserting a duplicate primary constraint, which in my local testing is somewhat reproducible and definitely causes the database to really react badly performance-wise.I tried to swarm the staging and local envs to see if something about lots of traffic could cause some unexpected bad-request 400s and thus maybe bubble-up as this error, but that never occurred, couldn't find any way at all to get the Java lib to even send a bad request on purpose.
