### ISSUE TITLE
Missing frontend test cases for design stepper component

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#1053]
**Is your feature request related to a problem? Please describe.**
Currently there are no frontend test cases for design stepper component.

**Describe the solution you'd like**
Write the missing frontend test cases for the  design stepper component.

**Comment by danoswaltCL** [comment]
Hold up! Is this already in progress? I fully support frontend unit tests but we should chat because the design-stepper will be going away. If we decide to start working on the UI redesign work that Zack has done, that effort may go to waste if it's sooner rather than later. We could definitely use tests in other places though.

Also, I feel like there's an important decision about frontend tests that needs to be decided together as a team; do we include Angular _component_ testing in our unit testing specs (i.e. using the TestBed to test things like click events / DOM interactions / and anything depending Angular lifecycle magic). If you've ever written Angular frontend tests with the boilerplate spec code that Angular generates, you probably hate it because it's so confusing to deal with the TestBed and Angular change-cycle side-effects. It makes it seems like that's what you're "supposed" to do, but because like, cool we can test button clicks and form entries, so we _should_ right?

My opinion and my experience is that while you can do that with Jest (or Jasmine), those aren't actually unit-tests, and they are not worth the effort. They are technically integration tests, as they are dependent on side-effects that simulate the DOM and/or depend on calling things outside of the function-under-test. This makes them brittle and expensive to maintain, and they screw up other tests very easily if you aren't careful about how you're mocking component state. Also, they make the test suite run way way slower...

If we're doing frontend component unit tests, I'd strongly suggest that they should concentrate on functional unit-test coverage without any external library (including/especially Angular) or DOM "side-effects". Then you can lock down all side-effects and concentrate on purely isolation testing the actual javascript. That's where most of the bugs are going to live anyway. We don't really need the TestBed at all (usually, it can help). We shouldn't even really need to be testing anything that Angular does under the hood. Google did that testing already. These kinds of unit tests are massively easier to write and maintain, and are much more likely to actually help you catch and fix bugs reliably than some crazy twisted test that always breaks because some component interaction has changed that has nothing to do with the actual function being tested.

**Comment by ppratikcr7** [comment]
> Hold up! Is this already in progress? I fully support frontend unit tests but we should chat because the design-stepper will be going away. If we decide to start working on the UI redesign work that Zack has done, that effort may go to waste if it's sooner rather than later. We could definitely use tests in other places though.
> 
> Also, I feel like there's an important decision about frontend tests that needs to be decided together as a team; do we include Angular _component_ testing in our unit testing specs (i.e. using the TestBed to test things like click events / DOM interactions / and anything depending Angular lifecycle magic). If you've ever written Angular frontend tests with the boilerplate spec code that Angular generates, you probably hate it because it's so confusing to deal with the TestBed and Angular change-cycle side-effects. It makes it seems like that's what you're "supposed" to do, but because like, cool we can test button clicks and form entries, so we _should_ right?
> 
> My opinion and my experience is that while you can do that with Jest (or Jasmine), those aren't actually unit-tests, and they are not worth the effort. They are technically integration tests, as they are dependent on side-effects that simulate the DOM and/or depend on calling things outside of the function-under-test. This makes them brittle and expensive to maintain, and they screw up other tests very easily if you aren't careful about how you're mocking component state. Also, they make the test suite run way way slower...
> 
> If we're doing frontend component unit tests, I'd strongly suggest that they should concentrate on functional unit-test coverage without any external library (including/especially Angular) or DOM "side-effects". Then you can lock down all side-effects and concentrate on purely isolation testing the actual javascript. That's where most of the bugs are going to live anyway. We don't really need the TestBed at all (usually). We shouldn't even really need to be testing anything that Angular does under the hood. Google did that testing already. These kinds of unit tests are massively easier to write and maintain, and are much more likely to actually help you catch and fix bugs reliably than some crazy twisted test that always breaks because some component interaction has changed that has nothing to do with the actual function being tested.

Yeah you are right, we had started a bot on this but wont continue further as it wont be used in future. Let's discuss more in the only-dev meeting later.

**Comment by amurphy-cl** [comment]
This is a lot of work that will become irrelevant with design refresh. Closing for now.
