### ISSUE TITLE
Experiment import erases payload data

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#1074]
**Version where bug was found:**
5.0.10

**Describe the bug**
Importing an experiment with payloads results in all payloads being reset to the condition name. This is a problem when condition names and payloads differ. Note that the export seems to correctly preserve payloads. 

**To Reproduce**
Import an experiment using the import button. 
View Design->Payloads
See that payload data did not import

**Expected behavior**
Payloads should be imported to match values in the json.

**Comment by Yagnik56** [comment]
This issue is resolved in `bugfix/1054-validationErrors` branch PR, `parentCondition` and `decisionPoint` id were stored as null due different conditionPayload format while creating and import experiment. That created issue in importing experiment with payloads name and editing conditionPayload value addressed in PR I mention.
