### ISSUE TITLE
Simple Export summary not including all expected users

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1075]
**Version where bug was found:**
4 or 5

**Describe the bug**
Some users logged by Mathstream as receiving experiment conditions that were assigned and marked in UpGrade are not showing up in the exported data.

**Comment by ppratikcr7** [comment]
@danoswaltCL We would need the prod data dump for this.

**Comment by amurphy-cl** [comment]
Update on this issue: Ben and I looked into this today and noted a few things. In a MATHstream data export of 569 unique users that should have been enrolled in experiment id `48a9cf27-710e-4c2c-a864-3739815c52c5`, 47 of them were not in the UpGrade data export. None of those 47 appear to have hit `/mark` for that experiment id, but 30 of them `/mark`ed for other experiment ids. Right now it's unclear whether these users failed to `/mark` because of UpGrade prod issues or other unknown reasons, because of some problem with UpGrade condition assignment, or some problem in the MATHstream database. The MATHstream team is cross-checking user assignment data in their data tables to verify condition assignment from their end.

**Comment by amurphy-cl** [comment]
MATHstream team per tcowell couldn't track down the data due to problems with data logging on their side, next steps are to conduct an AA test. Will close this and create a new ticket if we find data discrepancy issues.
