### ISSUE TITLE
Exclusions are not handled as expected in mark call and code needs optimization

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#1301]
**Version where bug was found:**
e.g "5.1.0"

**Describe the bug**
Currently the various exclusions codes are not stored in the DB for simple and within subject experiments. Mark call code for exclusions needs optimization to not call various code blocks for all experiment state. We are also storing multiple rows for Individual Enrollments for within subject experiments and we are also storing multiple rows for monitored decision point table for experiment level exclusions.

**To Reproduce**
Steps to reproduce the behavior for few exclusions, or refer to the detailed [document](https://docs.google.com/document/d/1e-FPHZ5ofo1u_3MSuhf7VVJdMQmQ2U9vQGf_luyoCHo/edit?usp=sharing) for all exclusion codes:
1. Try to exclude a user who is on exclusion list using a segment or individual exclusion list.
2. Once you hit /mark api for the user, you wont see its Data as the table is not getting populated with the reason for exclusion.

**Expected behavior**
Exclusions should work as expected for the above scenario.

**Comment by bcb37** [comment]
After testing this, I have a question about the behavior outlined in the linked document:

If a participant is excluded because their group has been excluded, a record is added to the `individual_exclusion` table with PARTICIPANT_ON_EXCLUSION_LIST code, in addition to a record being added to the `group_exclusion` table with GROUP_ON_EXCLUSION_LIST code. Do we want both of those records created in that case?

Also, if a student with no excluded groups enrolls with a given working group, and then another student enrolls with the same working group, but with an already excluded group in their group list, that working group will be excluded. However, any previous enrollments from that working group are still there. Is this a concern?

**Comment by VivekFitkariwala** [comment]
In case of individual consistency, we need a record in that table.

The second one is a concern. This is similar to the discussion we had on this [ticket](https://github.com/CarnegieLearningWeb/UpGrade/issues/1404)
