### ISSUE TITLE
FF Bug: Duplicated list

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#1816]
Observed in demo, in some circumstance of navigating between root and detail page, the Include List table duplicated an entry.

@zackcl do you know the steps to reproduce?

**Comment by zackcl** [comment]
Yes, you can add an inclusion list and then simply refresh the details page to see the duplicated list. I believe this happens due to a newly added effect from 2 days ago (#1759):

```
  upsertFeatureFlagInclusionList$ = createEffect(() =>
    this.actions$.pipe(
      ofType(FeatureFlagsActions.actionAddFeatureFlagInclusionList),
      map((action) => action.list),
      withLatestFrom(this.store$.pipe(select(selectSelectedFeatureFlag))),
      switchMap(([list, flag]) => {
        const request = {
          flagId: flag.id,
          ...list,
        };
        return this.featureFlagsDataService.addInclusionList(request).pipe(
          map((listResponse) => FeatureFlagsActions.actionUpdateFeatureFlagInclusionListSuccess({ listResponse })),
          catchError((error) => of(FeatureFlagsActions.actionUpdateFeatureFlagInclusionListFailure({ error })))
        );
      })
    )
  );
  ```
  I think this had been replaced with `addFeatureFlagInclusionList$` but somehow got included again in the PR. Commenting out that effect fixed the duplication issue for me. I can create a PR to remove this code.

**Comment by bcb37** [comment]
QA: not seeing duplication.
