### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'includes') when clicking "Add Experiment"

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#1944]
**Version where bug was found:**
6.0.0

**Describe the bug**
When the "Add Experiment" button is clicked, I get `TypeError: Cannot read properties of null (reading 'includes')` error in the browser console, as the stepper modal appears.

**To Reproduce**
1. Go to Experiments page
2. Click on 'Add Experiment' button
3. See error on the console

**Expected behavior**
The error should not occur.

**Additional context**
Full error log:
```
main.2e8f5ed4ef065937.js:1 ERROR TypeError: Cannot read properties of null (reading 'includes')
    at 795.c837925cf01b6b31.js:1:98181
    at Array.filter (<anonymous>)
    at Object.next (795.c837925cf01b6b31.js:1:98088)
    at L.next (main.2e8f5ed4ef065937.js:1:401413)
    at K._next (main.2e8f5ed4ef065937.js:1:401094)
    at K.next (main.2e8f5ed4ef065937.js:1:400787)
    at main.2e8f5ed4ef065937.js:1:413197
    at d._next (main.2e8f5ed4ef065937.js:1:411187)
    at d.next (main.2e8f5ed4ef065937.js:1:400787)
    at main.2e8f5ed4ef065937.js:1:414092
```

**Comment by RidhamShah** [comment]
The error encountered when clicking the "Add Experiment" button was caused by an issue with the metric structure, likely due to an improper configuration in the .env file. As the metric structure has been updated, it now requires a context array as one of its properties. However, it was receiving null or undefined instead of an array, which prevented the application from reading the metric's context and resulted in the error.

The solution provided in this PR will address the immediate bug, but the primary focus should be on correcting the metric data configuration in the .env file
