### ISSUE TITLE
Experiment enrollment status and History on dashboard 

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#25]
After an experiment status has changed to Enrolling, you can't see when enrollment started. We have when the experiment was "created on", but will need to know when enrollment was started and when it was completed, during and after experiment enrollment.

**Comment by YashilDepani** [comment]
@amurphy-cl, I have made a [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/65) regarding this issue. In this PR, whenever the state changes for the experiment (say from inactive to enrolling, from enrolling to enrollment complete, etc) we have added the time logs.
1. When the user changes the state of the experiment, it keeps track of every transition of state in the DataBase.
2. On clicking at the Time Logs in the UI, the modal lists transition from enrolling to enrollment-Complete and vice versa for the experiment.
![image](https://user-images.githubusercontent.com/51193749/124458615-d2751780-ddaa-11eb-95c5-523dd77c5d22.png)
![image](https://user-images.githubusercontent.com/51193749/124458633-d7d26200-ddaa-11eb-94a6-711e5dd6a031.png)
![image](https://user-images.githubusercontent.com/51193749/124458649-dd2fac80-ddaa-11eb-870b-e1dbc351dc6e.png)

**Comment by amurphy-cl** [comment]
This looks good. Thanks for the clear description of the update! @msandbothe can you review the PR when you get a chance?

**Comment by YashilDepani** [comment]
@amurphy-cl and @msandbothe there is one point to be noted before the PR of this issue is merged. 
we just need to make sure the experiments are not in enrolling state before it is merged. Otherwise, the row data will be inconsistent. Enrollment complete, inactive, canceled anything is fine.

(More in detail) 
If the experiment is in enrolling state and then the PR is merged. The code doesn't know yet that it is in enrolling state as no transition has happened (image 1). Now, the data will be inconsistent whenever it moves from enrolling to complete state and back to enrolling state (image 2). As you can see the "start-time" is ahead of  "end time".
If the experiment is in an enrollment completed/inactive state, then there will be no issues. (image 3, image 4)
![image](https://user-images.githubusercontent.com/51193749/124798909-8de7a880-df71-11eb-9106-687e65cf4c4d.png)
![image](https://user-images.githubusercontent.com/51193749/124798927-92ac5c80-df71-11eb-9396-d367b3f43961.png)
![image](https://user-images.githubusercontent.com/51193749/124798938-963fe380-df71-11eb-8250-52b55cbec9be.png)
![image](https://user-images.githubusercontent.com/51193749/124798952-99d36a80-df71-11eb-9765-f9ebd2db0d22.png)

**Comment by YashilDepani** [comment]
@amurphy-cl and @msandbothe, I have fixed the above issue. You can ignore my previous comment.
