### ISSUE TITLE
Adding description in the metric metadata

### ISSUE THREAD

**Issue by nirmalpatel** [CarnegieLearningWeb/UpGrade#251]
More details in the Metrics GDoc.

**Comment by zackcl** [comment]
The UI for adding the Metrics will look like the following: (It will be part of the experiment wizard)
<img width="500" alt="Experiments - Add Experiment-03-16" src="https://user-images.githubusercontent.com/90279765/152612371-24fc69a9-7165-4053-a85a-49b2d044d357.png">

We decided to use  "Description" instead of "Name" and include the `description` in the metrics metadata so it can be autocompleted as the default description when the user selects "Metric" and "Statistic" in the UI. The default description will be autocompleted in the following format as you can see from the above screenshot:
```
description_from_metadata (statistic)
```
And the user will be able to edit the description further when needed.

Here's the link to the [Metrics Google Docs](https://docs.google.com/document/d/1U6Mw0KB82EDpd9W99Kl5Rud1PMMatu0XJcmIBiguAL0/edit?usp=sharing). On pages 5 and 6, you can find how the `description` will be added to the metadata. (Or see the below examples)

Simple Metric Example:
```
{
    "metric": "totalTimeSeconds",
    “description”: “The total time that the student has used MATHia”,
    "datatype": "continuous"
  },
```
Grouped Metric Example:
```
{
    "groupClass": "masteryWorkspace",
    "allowedKeys": [
      "calculating_area_various_figures",
      "Compare_functions_diff_reps_quadratic",
      ...other workspace ids...
    ],
    "attributes": [
      {
        "metric": "timeSeconds",
        “description”: “The amount of time to complete this workspace”,
        "datatype": "continuous"
      },
      {
        "metric": "hintCount",
        “description”: “The number of hints in {key}”, // {key} will be replaced with the Workspace ID in UpGrade
        "datatype": "continuous"
      },
      ...
```

If we apply this change to UpGrade, the [`METRICS` variable in the `.env.example` file](https://github.com/CarnegieLearningWeb/UpGrade/blob/main/backend/packages/Upgrade/.env.example#L86) should be changed to the following:
```
METRICS = [{"metric":"totalTimeSeconds","description":"The total time that the student has used MATHia","datatype": "continuous"},{"groupClass":"masteryWorkspace","allowedKeys":["calculating_area_various_figures","Compare_functions_diff_reps_quadratic"],"attributes":[{"metric":"timeSeconds","description":"The amount of time to complete this workspace","datatype":"continuous"},{"metric":"hintCount","description":"The number of hints in {key}","datatype":"continuous"}]}]
```

And the `POST /api/metric/save` request will require a body like this:
```
{
    "metricUnit": [
        {
            "metric": "totalTimeSeconds",
            "description": "The total time that the student has used MATHia",
            "datatype": "continuous"
        }
    ]
}
```

**Comment by zackcl** [comment]
Here's an updated design:

* Removed the number column

<img width="500" alt="Experiments - Add Experiment-03-16" src="https://user-images.githubusercontent.com/90279765/157068322-feb8d0d8-18c0-4ca5-9411-312a12600632.png">

**Comment by amurphy-cl** [comment]
Closing this since @zackcl did extensive UI redesign that we reviewed elsewhere
