### ISSUE TITLE
Update enrollment codes to enums

### ISSUE THREAD

**Issue by SritterCL** [CarnegieLearningWeb/UpGrade#27]
It looks like the enrollment codes are strings, rather than numbers (enums would be OK).

It also looks like enrollment code was set to null on an error (rather than an error code). Here's my suggestion:
0 - participant was included in experiment
1 - participant excluded due to unspecified error
2 - participant reached experiment point prior to experiment enrolling
3 - participant was on exclusion list
4 - participant’s group was on exclusion list
5 - participant excluded due to group assignment logic
6 - participant excluded from group-assignment experiment - no group specified

(we should try not to use CarnegieLearningWeb/educational-experiment-service#1 - any "common" errors should get their own code).

**Comment by nirmalpatel** [comment]
@SritterCL we had some more discussion on this. The first step towards solving this is to finalize our first list of codes, then publish those as enums in the `upgrade_types` NPM package, and then go on to change the backend code.

Here is your last list of codes where I split out the INCLUDE into ASSIGN and ENROLL:

1. **ASSIGN** - participant was assigned a condition in the experiment
2. **ENROLL** - participant was enrolled in the experiment (as a result of the mark() call)
3. **ERROR** - participant excluded due to unspecified error
4. **REACHED_PRIOR** - participant reached experiment point prior to experiment enrolling
5. **PARTICIPANT_ON_EXCLUSION_LIST** - participant was on the exclusion list
6. **GROUP_ON_EXCLUSION_LIST** - participant’s group was on the exclusion list
7. **EXCLUDED_DUE_TO_GROUP** - participant excluded due to group assignment logic
8. **NO_GROUP_SPECIFIED** - participant excluded from the group-assignment experiment - no group specified

We don't know when we will assign the ERROR as the enrollment code, but we can publish it as an enum for now and find out the logic for it later. Let us know if you think the list is good to go.

@msandbothe if we change the `upgrade_types` NPM package and merge the PR, will it get published automatically in the public NPM repository?

**Comment by msandbothe** [comment]
>     7\. **EXCLUDED_DUE_TO_GROUP** - participant excluded due to group assignment logic

Can we have EXCLUDED_DUE_TO_GROUP_LOGIC

**Comment by msandbothe** [comment]
@jerith666 Do you know the answer to the publishing changes to `upgrade_types` NPM package? (@msandbothe if we change the upgrade_types NPM package and merge the PR, will it get published automatically in the public NPM repository?)

**Comment by jerith666** [comment]
I don't; @mfugate1 should be able to tell us.

I thought everything was here in one repo, though, so I'm curious why it's necessary to wait for an artifact to be published at all.

**Comment by ppratikcr7** [comment]
@SritterCL We had a discussion on this issue while working on it and we have decided to include one more enum called `INCORRECT_GROUP_OR_WORKING_GROUP = 'participant's group or working group is incorrect'`.

**Comment by SritterCL** [comment]
OK - In general, it's fine to add new codes. Ideally, ERROR should never come up, since everything's covered under a different code. I assume "group of working group is incorrect" means that the group/WG was specified but isn't a valid group.

**Comment by ppratikcr7** [comment]
Yes, you are right. It means that the group/WG was specified but isn't a valid group. I will update the enum with the new suggested name.

**Comment by amurphy-cl** [comment]
@ppratikcr7 status update on this issue pls?

**Comment by ppratikcr7** [comment]
@amurphy-cl Majority of the changes were done. We will pick this up again.

**Comment by VivekFitkariwala** [comment]
During the implementation of #342 we have added enrollment and exclusion tables and the above code will be split into two different type `ENROLLMENT_CODE` and `EXCLUSION_CODE`
```
export enum ENROLLMENT_CODE {
  ALGORITHMIC = 'participant enrolled via algorithm',
  GROUP_LOGIC = 'participant enrolled due to group enrollment',
}

export enum EXCLUSION_CODE {
  ERROR = 'participant excluded due to unspecified error',
  REACHED_PRIOR = 'participant reached experiment prior to experiment enrolling',
  REACHED_AFTER = 'participant reached experiment during enrollment complete',
  PARTICIPANT_ON_EXCLUSION_LIST = 'participant was on the exclusion list',
  GROUP_ON_EXCLUSION_LIST = 'participant’s group was on the exclusion list',
  EXCLUDED_DUE_TO_GROUP_LOGIC = 'participant excluded due to group assignment logic',
  NO_GROUP_SPECIFIED = 'participant excluded due to incomplete group information',
  INVALID_GROUP_OR_WORKING_GROUP = "participant's group or working group is incorrect",
}
```

`ASSIGN` and `ENROLL` codes are removed as now we are not storing the assignments but only the enrollments. Let us know if any changes are required?

**Comment by amurphy-cl** [comment]
@VivekFitkariwala this looks good, I'll close this now.

**Comment by VivekFitkariwala** [comment]
Reopening because the code is in PR.
