### ISSUE TITLE
Local Docker Setup commands not working after new changes to it

### ISSUE THREAD

**Issue by ppratikcr7** [CarnegieLearningWeb/UpGrade#295]
We tried setting up local docker setup at our end in multiple systems. We are facing the below issues:

1. The commands `make setup-local` and even new command stated by @danoswaltCL which is `make setup` doesn't seem to work to install the npm modules. When I checked through the Makefile in dev branch, there is no command for `setup`, instead we still have `setup-local` which we had before nix changes and that time it was working for me. Can @kawcl or @danoswaltCL verify at their ends and let us know. (For now we are running `npm ci` commands manually in all folder locations to install packages )

![image](https://user-images.githubusercontent.com/33730817/156507699-0d027274-be8e-4f60-ac36-37cb47aeb3d4.png)

2. We see 2 errors (frontend and backend error) while running the `make` command to generate all the docker images and start them. Though, I don't know if they are affecting some functionality or not.

![image (1)](https://user-images.githubusercontent.com/33730817/156508607-bc345c25-6fe3-4032-9895-e844953f11f8.png)

3. This is my system specific, I am not able to view logs on right clicking container and selecting `View Logs` with the error: docker command not found. Though it works for yashil. Any help on this may be a plus for me.

![Screenshot 2022-03-03 at 11 53 37 AM](https://user-images.githubusercontent.com/33730817/156509032-55cf889e-9a70-440c-9770-02cabae6112f.png)

**Comment by kawcl** [comment]
hey @ppratikcr7,

Issue 1 
- The Makefile command should be `make setup-local` in the dev branch.  When that command is used the Makefile will run `./docker-setup.sh -l`.  This script uses [NixOS](https://nixos.org/) so that the node & npm version is standardized for everyone. The setup for the NixOS script is in `docker.nix`, right now it will make sure everyone installs the node_packages using node v12. Whenever we migrate to node v16 we will need to update to `nodejs-12_x` in `docker.nix` to `nodejs-16_x`.  Long story short, the script uses NixOS so that means people will need to [install](https://nixos.org/download.html#nix-install-linux) that on their computer right now. I'm contemplating using docker again for this step to run nix in a container for this step so people wouldn't need to explicitly install it, but I need to work on that.

Issue 2
- I'm not exactly sure on this one because I couldn't find any info to confirm what I think these errors are for.  However they haven't affected functionality for me or anyone else that I know has tried this step so far here so I think they are OK for now.

Issue 3
- I'm not sure why this is occurring.  It seems it might be an issue with the vscode plugin. This is the plugin's [github](https://github.com/microsoft/vscode-docker/issues?q=is%3Aissue+is%3Aopen), though I haven't found anything with a quick search. Otherwise maybe try reinstalling the plugin?

**Comment by jerith666** [comment]
> I'm contemplating using docker again for this step to run nix in a container for this step so people wouldn't need to explicitly install it, but I need to work on that.

Interesting idea.  I'd rather require only nix (and use nix to get docker), but that might not be possible since docker requires a daemon to be running.

**Comment by ppratikcr7** [comment]
@kawcl Thanks for the clarifications, let us try as per your comments. We will get back in case we still face any issue.

**Comment by danoswaltCL** [comment]
on point 3, it is probably issue with it finding docker in PATH, `which docker` can show where it's installed, could `echo $PATH` to see if that PATH seems reachable.

Other thing to try would be to open up the docker desktop app, all same things are going to be found there, that's where I tend to look at the logs anyway, and some things I see googling t`docker command not found` seem to suggest that after opening the docker app the first time, in background it fixed the PATH issue and `docker` commands worked as expected.

**Comment by kawcl** [comment]
> 

Yea I'm not sure which direction would be best..
Have nix maintain the dependencies and run the docker containers or have docker run and manage nix which manages the dependencies.  There is a [docker image](https://hub.docker.com/r/nixos/nix) for nix but a quick search for how to use it properly hasn't proven that fruitful. I have, however, found a source for [running docker containers with nix](https://nix.dev/tutorials/building-and-running-docker-images)

I'd like to make it so you only need to install either-or on your machine instead of both.

I have to take a break from this though to focus on some other work right now, I'll try and revisit it soon.

**Comment by ppratikcr7** [comment]
@kawcl Thanks, installing Nix did work for me, I am able to run `make setup-local` now. 

Let me know if this issue should be closed if we don't want anything else to be discussed here on this ticket, else it's fine if we continue to discuss further on Nix.

**Comment by ppratikcr7** [comment]
@danoswaltCL I will check with your resolution and let you know. Thanks :)

**Comment by ppratikcr7** [comment]
@kawcl We also observed a weird behaviour of docker script where it creates the containers with a different name. For e.g.: Instead of `upgrade-postgres-1` the container name is `upgrade_postgres_1`. So, we have to change the environment variable in the local docker env file: `TYPEORM_HOST=upgrade-postgres-1`. Any idea about this inconsistency?

**Comment by danoswaltCL** [comment]
@ppratikcr7 

Yes we noticed before and we should document it, this is likely the issue where in docker setting `Use Docker Compose V2` needs to be toggled on:

<img width="578" alt="image" src="https://user-images.githubusercontent.com/97542869/157051819-b932deac-0f61-4acb-b0b1-5c3604771195.png">

**Comment by kawcl** [comment]
@ppratikcr7 Dan would be correct on this, depending on which version of compose you are using it append names differently with "_" or "-"

**Comment by ppratikcr7** [comment]
Okay, thanks. Yeah, we should document all this thing in our Upgrade documentation.

**Comment by ppratikcr7** [comment]
@kawcl @danoswaltCL Should we close this issue?
