### ISSUE TITLE
Allow experiment detail page to open in new window/tab without re-auth

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#353]
As stated above. Would be nice to open up experiment details in new tabs without authing every time.

**Comment by danoswaltCL** [comment]
I can't reproduce this, new tabs open for me without having to auth. It may be browser settings?

**Comment by ppratikcr7** [comment]
I can reproduce this. May be then this is a browser setting. But, we should be able to set this setting from Upgrade and not let them auth again and again.

**Comment by ppratikcr7** [comment]
> I can reproduce this using Safari and unchecking the "Prevent cross-site tracking" option allows me to launch tabs and retain my authentication. Are you able to reproduce this in another browser or is Safari's Intelligent Tracking Prevention the problem? Just want to narrow the issue before I dive into a rabbit hole

You are right, I am able to retain my auth in chrome and in safari I had to uncheck the setting you mentioned. Is there a way we can check that setting for safari browser and disable it? Is that allowed, as its a privacy settings that we shouldn't change without user's consent.

**Comment by danoswaltCL** [comment]
I think if we're feeling pretty sure that the only way we can reliably reproduce is to loosen personal browser settings, and not because of some bug with how cookies / session data is being stored, I think that maybe the thing is to mention this as a known browser behavior in our documentation on gitbook, and not an application bug.

We could say that due to privacy settings, this may happen, show how to disable the settings, but leave that choice up to the user. @amurphy-cl thoughts?

**Comment by amurphy-cl** [comment]
Hmm, I got it to work in Safari but am still getting auth requests in Chrome (even though I have the "do not track request" unchecked. Agree that this should be in documentation though.

**Comment by jreddig** [comment]
I wasn't able to reproduce this issue in Chrome or Firefox 😕 But I added documentation for the Safari cross-site tracking checkbox

**Comment by mswartzCL** [comment]
Potential fix is to move auth to server side instead of client side. Will need some more research. Moving back to backlog.
