### ISSUE TITLE
UI design for factorial/partial factorial experiment support

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#392]
Tracking UI design in this issue. Algorithm development is tracked in #393 

@zackcl could you link or attach your figma designs here?

## Note: Please refer to this comment below: https://github.com/CarnegieLearningWeb/UpGrade/issues/392#issuecomment-1466608087 which shows the UI design for the new factorial experiment design.

**Comment by zackcl** [comment]
The key frames:

<img width="500" alt="Experiments - Add Experiment-02-13" src="https://user-images.githubusercontent.com/90279765/179656718-c137795d-73d3-4fd3-82d2-5249a1e1da05.png">
<img width="500" alt="Experiments - Add Experiment-02-14" src="https://user-images.githubusercontent.com/90279765/179656734-dadb21a8-e81a-4162-b100-36967c0dcdea.png">
<img width="500" alt="Experiments - Add Experiment-02-15" src="https://user-images.githubusercontent.com/90279765/179656744-40ca91f1-e13b-481f-8b42-45451bfe9686.png">
<img width="500" alt="Experiments - Add Experiment-02-18" src="https://user-images.githubusercontent.com/90279765/179656750-00a76391-d955-4b96-9c46-cbf2c57e2895.png">
<img width="500" alt="Experiments - Add Experiment-02-21" src="https://user-images.githubusercontent.com/90279765/179656762-c714557a-093f-4401-8f72-e2f6bbd6186a.png">
<img width="500" alt="Experiments - Add Experiment-02-31" src="https://user-images.githubusercontent.com/90279765/179656772-e0149b57-28ba-4da4-971f-e35929446483.png">
<img width="500" alt="Experiments - Add Experiment-02-32" src="https://user-images.githubusercontent.com/90279765/179656784-f21be141-64a4-448b-92e4-3fcb7062b134.png">
<img width="500" alt="Experiments - Add Experiment-02-33" src="https://user-images.githubusercontent.com/90279765/179656791-7b738324-d9f5-4ffa-9461-189ded6e1b38.png">
<img width="500" alt="Experiments - Add Experiment-02-42" src="https://user-images.githubusercontent.com/90279765/179656800-1b7aecbe-4e9f-441b-8248-e1042516e954.png">
<img width="500" alt="Experiments - Add Experiment-02-44" src="https://user-images.githubusercontent.com/90279765/179656808-29623193-b66f-4897-8495-3b8ff297f2ab.png">
<img width="500" alt="Experiments - Add Experiment-02-36" src="https://user-images.githubusercontent.com/90279765/179656815-d932e2ed-dd4c-4654-afbe-8785f4807ada.png">
<img width="500" alt="Experiments - Add Experiment-02-38" src="https://user-images.githubusercontent.com/90279765/179656820-47b8082d-5ed3-41b5-b58e-85e01fc0bb2f.png">

**Comment by mswartzCL** [comment]
@zackcl Hi Zack! Can you please refresh the content of this item with your latest UI designs. I think the links are probably still correct but the screenshots are out of date.

**Comment by zackcl** [comment]
@mswartzCL Sure, I will do it once some of the design details are fixed (still need to settle on how the combination-aliases should be included in the `api/assign` response structure).

**Comment by zackcl** [comment]
@mswartzCL I've updated the content with the latest UI designs.

**Comment by zackcl** [comment]
Here's the updated UI design for factorial experiments as we discussed ([link to the document](https://docs.google.com/document/d/1yeK-8mH39RIc7AV5ioY6dcwdGA8RbSWt5e0zLqwavXA/edit?usp=sharing)).

Changes:
* Have a separate Decision Points table above the Factors table
* The factor row has a Description field instead of Site and Target
* The Alias column should be renamed to Payload
* The Conditions table has a Condition column instead of factor names
* No toggle button to switch between the Factors and Conditions table in the Design step
* As soon as there is more than one factor, the Conditions table will appear below the Factors table
* The whole modal would be scrollable as the content grows, but the modal's height would remain fixed, as it is now
* The details page should also be updated accordingly


<img width="500" alt="Experiments - Add Experiment-02-30 (2)" src="https://user-images.githubusercontent.com/90279765/224774545-046dba92-1175-4b47-bc18-a81478a98aa3.png">
<img width="500" alt="Experiments - Add Experiment-02-30 (3)" src="https://user-images.githubusercontent.com/90279765/224774580-489b1669-a518-48d8-86d7-76f1c8b4269c.png">
<img width="500" alt="Experiments - Add Experiment-02-30" src="https://user-images.githubusercontent.com/90279765/224774604-f5205925-966e-4a04-8057-5e0a0bc3bb44.png">
<img width="500" alt="Experiments - Add Experiment-02-30 (1)" src="https://user-images.githubusercontent.com/90279765/224774624-49187fe6-e7db-4369-95f9-b024d866d594.png">
<img width="750" alt="Experiment Detail - Design (Inactive) 7" src="https://user-images.githubusercontent.com/90279765/224783217-aa05db23-9136-484f-9b94-6091ab0f1b3f.png">
