### ISSUE TITLE
Create Experiment Modal: Metrics Step Design issues

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#412]
**Describe the bug**
User Interface for Metrics Step has design and user experience issues

**To Reproduce**
1. Create new experiment, or edit existing
2. Fill out first 3 steps

**Expected Behavior**
Table rows and headers differ from designs, and/or have unexpected behaviors:
 - Small Font sizes
 - Wide vertical spacing
 - Form fields have missing underlines
 - First item "Metric*" is a dropdown, but no triangle indicator given
 - Selected Items in "Metric" show as grey and disabled, which seems like a weird state
 - Description is required?

**Screenshots**
Expected:
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/97542869/176285349-45b21ba6-c742-441c-a846-6a073a9a34ae.png">

Actual:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/97542869/176285142-e17a2238-f366-415f-8d4e-84c1987bab5f.png">
<img width="962" alt="image" src="https://user-images.githubusercontent.com/97542869/176286321-2cb32687-0b2a-414c-a903-23ac53f89f66.png">

**Additional context**

**Comment by ppratikcr7** [comment]
@danoswaltCL Few notes on the above expected behaviour:

Small Font sizes (Will do that)
Wide vertical spacing (Will do that)
Form fields have missing underlines (Will do that, but it's not there in figma design. If that's required, will have to do that in other stepper pages as well)
First item "Metric*" is a dropdown, but no triangle indicator given (Will do that, make it select option)
Selected Items in "Metric" show as grey and disabled, which seems like a weird state (This is as it was in earlier monitored metrics page and it is to avoid various issues in case of repeated metrics)
Description is required? (Yes, this will be the name of the query in experiment details page)

**Comment by ppratikcr7** [comment]
@zackcl okay, so let's confirm this in the meeting. Do we want metrics to be type ans select or dropdown.

**Comment by jreddig** [comment]
Per the discussion on 7/7, a combo box is acceptable, but it should validate against the metadata
