### ISSUE TITLE
Load testing large numbers of of explicit-included or excluded individuals

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#438]
What happens if we have an explicit-include or -exclude list that is hundreds of thousands of entries long? How does UpGrade handle this? Does it create a bottleneck?

**Describe the solution you'd like**
UpGrade should be able to handle this type of long list of individual users, but we should test it in development first.

**Comment by jreddig** [comment]
First test: created a 10,010 student ids segment and a 1400 school ids segment. Experiment is set to include the school ids and exclude the student ids. Attempted to enroll 300 concurrent users via locust - all users had an included school id and 50% of the users had an excluded student id.  While the assignment rules were obeyed, the average latency shot up to over 50 seconds and the db utilization peaked at 15%.
<img width="871" alt="Screen Shot 2022-07-13 at 1 38 55 PM" src="https://user-images.githubusercontent.com/97543136/178796372-375bb7e7-c014-4fed-b5d1-664b7a5bce61.png">
<img width="1019" alt="Screen Shot 2022-07-13 at 1 39 09 PM" src="https://user-images.githubusercontent.com/97543136/178796373-96970893-e871-4400-b563-5e593f74d288.png">

**Comment by jreddig** [comment]
Next experiment was include all, exclude the 10,010 student segment. Attempted to enroll 300 concurrent users via locust - 50% of the users had an excluded student id. Similar behavior observed, latency peaked at 50s an db cpu utilization above 25%
<img width="1024" alt="Screen Shot 2022-07-15 at 11 42 50 AM" src="https://user-images.githubusercontent.com/97543136/179259062-fdf3d042-2813-4036-8f1c-4cb8a465c2b6.png">
<img width="904" alt="Screen Shot 2022-07-15 at 11 43 01 AM" src="https://user-images.githubusercontent.com/97543136/179259074-45673b31-8a30-421f-bd11-b29c37db05d1.png">

**Comment by danoswaltCL** [comment]
does it report which calls were running slowest?

**Comment by jreddig** [comment]
Yes, /mark was by far having the most trouble and failures, followed by /assign then /log. The failures are all 504 GATEWAY_TIMEOUT
<img width="1107" alt="Screen Shot 2022-07-15 at 11 53 46 AM" src="https://user-images.githubusercontent.com/97543136/179260745-b3fdab91-dcf8-4ae6-b10d-d823faf1304b.png">
<img width="1347" alt="Screen Shot 2022-07-15 at 11 55 24 AM" src="https://user-images.githubusercontent.com/97543136/179260979-83ea210a-8445-49e7-a5fc-fd9fc8564f4d.png">

**Comment by RidhamShah** [comment]
We think that as there is a huge Segment present and it is called and checked for the user every time for mark and assign. A better solution for this scenario is to create a cache for this segment and fetched its value from it. We found a [cache manager](https://www.npmjs.com/package/cache-manager) which can be used for segment caching on the server side.

**Comment by nirmalpatel** [comment]
@danoswaltCL @jreddig we are evaluating one more option for speeding up the include/exclude algorithm implementation. We are trying to see if we can find segment memberships f a user using the SQL query and use that along with the segment dependency graph object to optimize the algorithm. Not sure if this can outperform the caching option, but we are evaluating both options...

**Comment by jreddig** [comment]
After the cache addition, seeing significantly better results! Same experiment setup, include 1400 schools, exclude 10k students. Set 300 concurrent users running against staging. Latency peaked at 20s and DB CPU Utilization peaked at 22%. Significantly less failures because the calls aren't timing out!
Latency
<img width="914" alt="Screen Shot 2022-08-04 at 1 35 25 PM" src="https://user-images.githubusercontent.com/97543136/182914905-e03abf09-c3dd-4821-bcea-8a5fb7251766.png">
DB CPU Utilization
<img width="884" alt="Screen Shot 2022-08-04 at 1 35 39 PM" src="https://user-images.githubusercontent.com/97543136/182914942-34676c34-d6c4-4864-9432-e72053fabc50.png">
<img width="1369" alt="Screen Shot 2022-08-04 at 1 35 45 PM" src="https://user-images.githubusercontent.com/97543136/182914951-a0360875-e649-40d7-8f34-b9638bf7b578.png">
<img width="1373" alt="Screen Shot 2022-08-04 at 1 36 02 PM" src="https://user-images.githubusercontent.com/97543136/182914956-41339eaa-ede9-4920-b1fc-505a1b98a0e7.png">
