### ISSUE TITLE
Support for differently-named conditions in coordinated decision points

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/UpGrade#457]
Currently we only support conditions with the exact same name when using Coordinated Decision Points (`control` or `variant`). We need to support unique names per decision point. 

**Describe the solution you'd like**
The solution will probably entail a small redesign of the UI for coordinated decision points, similarly to how we plan to do factorial experiments. See screenshot. 
<img width="1182" alt="Screen Shot 2022-07-21 at 11 11 37 AM" src="https://user-images.githubusercontent.com/65311369/180249576-a68d551f-33ad-4290-8223-d65bd35b6152.png">

**User Story**
As a researcher creating an experiment for XPRIZE, that has coordinated decision points, I want students’ condition assignments (e.g. NotificationVariant) to persist across all relevant workspaces involved in this experiment (e.g. 10 algebra workspaces with word problems). So if StudentA is assigned NotificationVariant in the experiment across workspaces worksheet_grapher and analyzing_step_functions, they should see the NotificationVariant in both of those workspaces, as well as any others listed in the coordinated decision points. Likewise, a student randomly assigned to the Control condition should see only Control workspaces for worksheet_grapher and analyzing_step_functions. If a user returns to the workspace for review mode, they should experience the same condition as they did the first time, unless the experient enrollment has completed, after which the Post Rule should manage user experiences. 

**Related Issues**
- [ ] https://github.com/CarnegieLearningWeb/UpGrade/issues/512

**Comment by SritterCL** [comment]
Just to spell this out, since I've confused myself about this before:

Within MATHia, UpGrade currently sends the condition name (either "NotificationVariant" or "Control" for all decision points. But MATHia actually needs the workspace name. So we need to send either "worksheet_grapher_NotificiationVariant" or "analyzing_step_functions_NotificationVariant," depending on the decision point.

There are still 2 conditions called NotificationVariant and Control that apply to all of the coordinated decision points (from the experimenter's perspective). But MATHia expects the workspace ID to be the same as the condition name. I can think of a couple of ways to fix this:

1. Add a field that allows the experimenter to define a condition code for each conditionxdecisionPoint in the experiment (e.g. you'd need to type in "analyzing_step_functions_NotificationVariant" in the appropriate place. Once we do context metadata, we could pass these codes so the experimenter wouldn't need to type them.
2. We could construct the codes, based on the condition name and the decisionPoint target. Since the target is the base workspace name, we could adopt the naming convention that workspace variants are always target_condition, so, when the target is "analyzing_step_functions" and the condition name is "NotificationVariant", we know to send "analyzing_step_functions_NotificationVariant". One downside is that this could be weird for experiments on decision points that aren't workspaces (anything that isn't a permanent decisionPoint), since "target" isn't meaningful for these. We'd also need to think through these naming conventions for factorial experiments.
3. Have MATHia do the naming convention work. It knows the base workspace ID, so it can construct "analyzing_step_functions_NotificationVariant" as the appropriate workspace name, if UpGrade tells it to use NotificationVariant.

**Comment by mswartzCL** [comment]
My vote is for option 1 above. That option allows the flexibility needed for MATHia and other clients with different approaches. This also fixes the issue we've discussed previously of having condition codes that are different in the client but should be treated as the same condition for coordination in UpGrade.

**Comment by amurphy-cl** [comment]
Adding my vote for option 1 as well.

**Comment by zackcl** [comment]
Can someone please explain to me what the problem with option 3 would be? Doesn't it solve all problems if MATHia constructs the workspace ID with the condition name to find a correct workspace?

**Comment by mswartzCL** [comment]
@zackcl I think that option 3 lacks clarity and transparency. Without the complete condition code, we add an additional dependency on and an additional mapping function to be implemented by the clients. For instance, we'd have to use data from UpGrade and data or code from the client together to know the actual condition code. In my experience, it can get really confusing when you are relying on multiple systems to understand key values, especially when trying to debug.

**Comment by danoswaltCL** [comment]
I have been scratching my head about this for days, I have to be missing something. I too have trouble understanding why #3 isn't preferred. The client has all the info it needs to handle this, right? Target + Condition?

If so, it seems like it's right to insist that the client manage the business logic to support mapping a condition to whatever they want it to do, not UpGrade. Isn't this the most decoupled and least complex option? Does UpGrade need to be implicated at all in this version? Otherwise we have more to coordinate, more context-metadata to manage and validate with the condtion-aliases, new UI, etc

**Comment by ppratikcr7** [comment]
@danoswaltCL @zackcl @jreddig We have mostly completed the backend part for this ticket and working on test cases. Below are the details for the backend structure and API response changes: https://gist.github.com/ppratikcr7/b4c5c18154994a650d29cc952fa3804f

**Comment by danoswaltCL** [comment]
yup, ty, will take a look today
