### ISSUE TITLE
Cannot create an experiment with equally weighted 14 conditions

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#477]
**Describe the bug**
If I try to create an experiment with equally weighted 14 conditions (or unknown N conditions), UpGrade complains that the weights don't sum up to 100 even though the "Weight Equally" checkbox is enabled.

**To Reproduce**
1. Go to the Experiments section in UpGrade
2. Click on the "Add Experiment" button
3. In the Design step, create 14 conditions while the "Weight Equally" checkbox is enabled, and then click "Next"
4. You will see a red message below the Conditions table saying "Assignment weights' sum must be 100"

**Expected behavior**
When the "Weight Equally" checkbox is enabled, the user should be able to create any number of conditions without having to modify the weights, and we should not allow modifying the weights when the checkbox is enabled.

**Screenshots**
<img width="750" alt="Screen Shot 2022-07-29 at 10 02 30 AM" src="https://user-images.githubusercontent.com/90279765/181776900-b834b4cb-7dd5-4b85-94b7-56f8f2248f84.png">

https://user-images.githubusercontent.com/90279765/181633710-78aad3d9-b50d-4d20-9ac5-facdc4e419ea.mov

**Comment by zackcl** [comment]
@ppratikcr7 The latest PR (https://github.com/CarnegieLearningWeb/UpGrade/pull/481) doesn't really fix this problem because if there are 14 conditions, the assignment weight becomes `parseFloat((100.0 / 14).toFixed(1));` which is `7.1`. And if we sum all the weights it becomes `7.1 * 14 = 99.4`. If we call the `Math.round()` function, then it is `99` and not `100`. Therefore equally weighted 14 conditions cannot be created with the current code.

Here's a quick example code to show why it won't work:

```
for (let i = 1; i <= 10000; i++) {
  const numConditions = i;
  const assignmentWeight = parseFloat((100.0 / numConditions).toFixed(1));
  const sum = assignmentWeight * numConditions;
  const sumRounded = Math.round(sum);
  if (sumRounded !== 100) {
    console.log("Error:", numConditions, assignmentWeight, sum, sumRounded);
    break;
  }
}
// Result: "Error:", 14, 7.1, 99.39999999999999, 99
```

I think we shouldn't modify the actual weight values with `toFixed(1)`. And I'm not sure how this affects the actual weighting in our experiments. If possible, I would suggest internally storing/calculating the actual `assignmentWeight` values without modifying the precision, but only modifying the values (with `toFixed(1)`) that are shown in the browser. I'm not sure how this would be possible in Angular though.

**Comment by danoswaltCL** [comment]
Okay, I didn't realize we were sending the displayed weights as the actual values, that's going to be a problem. Why are we validating this case anyway?

Here's a thought:
When the `Weight Equally` is unchecked, we send the bare values the user has entered. The user won't be entering irrational decimals. These should get validated to equal 100, and the backend should use those exact values.

In the case where `Weight Equally` IS checked, we can likely handle this differently than we currently are: we should definitely NOT be performing any 100 summing validation. We should NOT send any browser-calculated values to the backend at all in this case, because this is business logic that the UI should not be trusted to perform. The UI should send a value for `Weight Equally` is true, and in this case, the backend can handle creating precise weights. The values in the UI in this case should be for display only.

Let me know if that makes sense, the UI should be as dumb as humanly possible.

**Comment by zackcl** [comment]
Yes, I think it makes sense to calculate the precise weights in the backend when the `Weight Equally` is checked. And maybe we don't even need to call `validateExperimentDesignForm()` when `equalWeightFlag` is set to `true`. And get rid of things like `.toFixed(1)` and `Math.round()` in the backend so we can just use the user-entered values when the `Weight Equally` is unchecked.

**Comment by ppratikcr7** [comment]
@zackcl @danoswaltCL Maybe we can close this if the current PR resolves this 14 condition issue for now. We can track the relative weights approach in a separate [issue](https://github.com/CarnegieLearningWeb/UpGrade/issues/500).

**Comment by jreddig** [comment]
I dont see this issue with 6 conditions but I do for 14 conditions. Since we have a different solution described in issue #500  and are changing the look/feel of the weights column, is it alright if I move this bug out of QA to Done?
