### ISSUE TITLE
expPoint/experimentPoint and expId/partitionId/experimentId should be renamed to site and target

### ISSUE THREAD

**Issue by zackcl** [CarnegieLearningWeb/UpGrade#588]
**Describe the issue**
Currently, the `api/assign` request returns something like the following:

```
[
    {
        "expPoint": "add-point1",
        "expId": "add-id1",
        "assignedCondition": {...}
    }
]
```
The `expPoint` and `expId` should be renamed to `site` and `target`.

Also, the `api/mark` request requires something like the following body:
```
{
   "experimentPoint": "add-point1",
   "partitionId": "add-id1",
   "userId": "u1",
   "condition": null
}
```
The `experimentPoint` and `partitionId` should be renamed to `site` and `target`.

And the `api/mark` request returns something like the following:
```
{
    "createdAt": "2022-10-27T14:12:13.614Z",
    "updatedAt": "2022-10-27T14:12:13.614Z",
    "versionNumber": 1,
    "condition": null,
    "userId": "u1",
    "experimentId": "add-point1",
    "id": "30d57b11-6d6b-4e06-a074-b9848ab0068c",
    "experimentPoint": "add-id1"
}
```
 The `experimentPoint` and `experimentId` should be renamed to `site` and `target`.

**Comment by jreddig** [comment]
This change has been made, but because MathIA is using older client libs, sending site/target in the response object was causing unnecessary errors, so we added a function to rename site/target to point/id: https://github.com/CarnegieLearningWeb/UpGrade/blob/6eb9393d7c0df54e0e2c5d58ce3af3fe0665e6b5/backend/packages/Upgrade/src/api/services/ExperimentAssignmentService.ts#L1821
