### ISSUE TITLE
[UI] Edit an Experiment with stratification choices [placeholder]

### ISSUE THREAD

**Issue by danoswaltCL** [CarnegieLearningWeb/UpGrade#977]
**User Story**
As an experimenter, I want to edit an experiment that uses stratified sampling using the design-stepper

**Dependencies:**
#969
#975 

**Links**
(🟠 Link design prototype)

**Acceptance Criteria**
🟠 what are the rules for editing an experiment's stratification choices? can it happen only if not enrolling?

**Comment by zackcl** [comment]
QA: Passed

I can confirm that I can edit an experiment that uses stratified sampling using the design-stepper in "Inactive" status. And I cannot update the Assignment Algorithm and Stratification Factor if the experiment is in "Enrolling" status, which I believe is the expected behavior.

<img width="500" alt="Screenshot 2023-11-20 at 9 41 16 PM" src="https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/de822cb8-608f-490c-a503-8c8f62dcfb63">
